{"cells":[{"metadata":{"id":"view-in-github","colab_type":"text","slideshow":{"slide_type":"skip"}},"cell_type":"markdown","source":"<a href=\"https://colab.research.google.com/github/thfruchart/tnsi/blob/main/02/Modules_COURS2_Exception.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"},{"metadata":{"id":"CWv7UrjhS-6x","slideshow":{"slide_type":"slide"}},"cell_type":"markdown","source":"# Un premier exemple"},{"metadata":{"id":"AUlhH7qwTCtl","slideshow":{"slide_type":"fragment"}},"cell_type":"markdown","source":"Reprenons l'exemple du module `ensemble1`."},{"metadata":{"id":"oxv92K_Y6dSR","slideshow":{"slide_type":"subslide"},"trusted":true},"cell_type":"code","source":"# Contenu du module ensemble1.py\ndef cree_ensemble():\n    ''' crée un ensemble vide, pouvant contenir des entiers entre 0 et 366\n    implémenté sous la forme d'un tableau de booléens'''\n    return [False for i in range(367)]\n\ndef appartient(v,s):\n    ''' teste si une valeur v (de 0 à 366) appartient à l'ensemble s'''\n    return s[v]\n\ndef ajoute(v,s):\n    ''' ajoute la valeur v (de 0 à 366) à l'ensemble s'''\n    s[v]=True","execution_count":1,"outputs":[]},{"metadata":{"id":"HO_-NPgfTLNT","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"Que se passe-t-il si un utilisateur utilise ce module de la manière suivante :"},{"metadata":{"id":"SPeNmJIOS2wd","slideshow":{"slide_type":"fragment"},"trusted":true},"cell_type":"code","source":"s1 = cree_ensemble()\najoute(31, s1)\najoute(399, s1)","execution_count":2,"outputs":[{"output_type":"stream","text":"Traceback (most recent call last):\n  File \"<input>\", line 3, in <module>\n  File \"<input>\", line 13, in ajoute\nIndexError: list assignment index out of range\n","name":"stderr"}]},{"metadata":{"id":"41FbNFfOTdAs","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"Les deux premières instructions sont correctement exécutées, mais la troisième renvoie un message d'erreur... qui convient mal : expliquer pourquoi !"},{"metadata":{"id":"XGGmn8z2ToS9","slideshow":{"slide_type":"fragment"}},"cell_type":"markdown","source":"... "},{"metadata":{"id":"OlfI930BTq-k","slideshow":{"slide_type":"slide"}},"cell_type":"markdown","source":"# Notion d'exception"},{"metadata":{"id":"gslWD5bxTvu0","slideshow":{"slide_type":"fragment"}},"cell_type":"markdown","source":"Un module bien écrit doit pouvoir donner une information claire à l'utilisateur qui en a fait une utilisation incorrecte : les exceptions sont destinées à cet usage."},{"metadata":{"id":"UgEcfd6eWmxE","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"Liste de quelques exceptions courantes de python\n\n|exception|contexte|\n|:--------:|:------:|\n|NameError|nom de variable inexistant|\n|IndexError|accès à un indice invalide dans une liste ou un objet indexé |\n|ValueError|valeur incorrecte dans le contexte |\n|KeyError|accès à une clé inexistante dans un dictionnaire|\n|ZeroDivisionError|division par zéro|\n|TypeError|opération appliquée à des valeurs dont le type ne correspond pas|"},{"metadata":{"id":"IVLEbzexWTH7","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"# Lever une exception"},{"metadata":{"id":"kNUSK23WYTt3","slideshow":{"slide_type":"fragment"}},"cell_type":"markdown","source":"Une exception \n* met fin au programme en cours\n* informe du motif pour lequel le programme est interrompu"},{"metadata":{"id":"wNE1rVr9UEmF","slideshow":{"slide_type":"subslide"},"trusted":true},"cell_type":"code","source":"# Contenu du module ensemble1.py avec EXCEPTION\ndef cree_ensemble():\n    ''' crée un ensemble vide, pouvant contenir des entiers entre 0 et 366\n    implémenté sous la forme d'un tableau de booléens'''\n    return [False for i in range(367)]\n\ndef appartient(v,s):\n    ''' teste si une valeur v (de 0 à 366) appartient à l'ensemble s'''\n    return s[v]\n\ndef ajoute(v,s):\n    ''' ajoute la valeur v (de 0 à 366) à l'ensemble s'''\n    if type(v) != int :\n        raise TypeError(\"la valeur n'est pas de type int\")\n    if v<1 or v>366 :\n        raise ValueError(\"valeurs entre 1 et 366 uniquement\")\n    s[v]=True","execution_count":3,"outputs":[]},{"metadata":{"id":"hVt4mUB6UEmW","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"Observer l'exécution du code suivant :"},{"metadata":{"id":"cabFxzTGVqR4","slideshow":{"slide_type":"fragment"},"trusted":true},"cell_type":"code","source":"s1 = cree_ensemble()\najoute(31, s1)\najoute(399, s1)","execution_count":4,"outputs":[{"output_type":"stream","text":"Traceback (most recent call last):\n  File \"<input>\", line 3, in <module>\n  File \"<input>\", line 16, in ajoute\nValueError: valeurs entre 1 et 366 uniquement\n","name":"stderr"}]},{"metadata":{"id":"FWz9caiCYxDr","slideshow":{"slide_type":"fragment"},"trusted":true},"cell_type":"code","source":"ajoute(15.78, s1)","execution_count":5,"outputs":[{"output_type":"stream","text":"Traceback (most recent call last):\n  File \"<input>\", line 1, in <module>\n  File \"<input>\", line 14, in ajoute\nTypeError: la valeur n'est pas de type int\n","name":"stderr"}]},{"metadata":{"id":"dnqiDHdwV1xC","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"## reste à modifier la fonction `appartient`"},{"metadata":{"id":"J4VhyOTbWCoq","slideshow":{"slide_type":"subslide"},"trusted":true},"cell_type":"code","source":"def cree_ensemble():\n    ''' crée un ensemble vide, pouvant contenir des entiers entre 0 et 366\n    implémenté sous la forme d'un tableau de booléens'''\n    return [False for i in range(367)]\n\ndef appartient(v,s):\n    ''' teste si une valeur v (de 0 à 366) appartient à l'ensemble s'''\n    if type(v) != int :\n        return False\n    if v<1 or v>366 :\n        return False\n    return s[v]\n\ndef ajoute(v,s):\n    ''' ajoute la valeur v (de 0 à 366) à l'ensemble s'''\n    if type(v) != int :\n        raise TypeError(\"la valeur n'est pas de type int\")\n    if v<1 or v>366 :\n        raise ValueError(\"valeurs entre 1 et 366 uniquement\")\n    s[v]=True","execution_count":6,"outputs":[]},{"metadata":{"id":"VXiZfuc0Y_Ar","slideshow":{"slide_type":"subslide"},"trusted":true},"cell_type":"code","source":"s2 = cree_ensemble()\najoute(310, s2)\najoute(57,s2)\nprint(appartient(5899, s2))\nprint(appartient(58.3, s2))","execution_count":7,"outputs":[{"output_type":"stream","text":"False\nFalse\n","name":"stdout"}]},{"metadata":{"id":"tDcUklosZcC8","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"# Mise à jour de l'interface du module `ensemble1`"},{"metadata":{"id":"NMbRfgQ6uhPU","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"\n|fonction           |description|\n| :--------------- :| :-------- :|\n|  `cree_ensemble()` |  crée un ensemble vide de dates|\n| `appartient(v,s)`  | renvoie `True` si et seulement si la date `v` est dans l'ensemble `s` |\n| `ajoute(v,s)`      | ajoute la date `v` (de type `int`) dans l'ensemble `s` si $1\\leq v \\leq 366$ et renvoie une exception `ValeurError` sinon|\n\n"},{"metadata":{"id":"x9KWChrVWMHj","slideshow":{"slide_type":"slide"}},"cell_type":"markdown","source":"# Rattraper une exception"},{"metadata":{"id":"pcGhf3xGWWyH","slideshow":{"slide_type":"fragment"}},"cell_type":"markdown","source":"Un programme peut prévoir quoi faire dans le cas où certaines exceptions surviennent. "},{"metadata":{"id":"-zhf3Pziao_u","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"## Exemple 1 : saisie d'un entier"},{"metadata":{"id":"_bqePULTad2C","slideshow":{"slide_type":"fragment"},"trusted":true},"cell_type":"code","source":"try:\n    n = int(input('entrer un entier : '))\nexcept ValueError :\n    print(\"Entrer un nombre entier valide\")","execution_count":11,"outputs":[{"output_type":"stream","text":"entrer un entier : alkjh\nEntrer un nombre entier valide\n","name":"stdout"}]},{"metadata":{"id":"28SozfOvbLMd","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"## Exemple 2 : saisie répétée, jusqu'à obtenir un entier valide"},{"metadata":{"id":"Vsle7f-CbUY2","slideshow":{"slide_type":"fragment"},"trusted":true},"cell_type":"code","source":"print('entrer un entier')\nboucle = True\nwhile boucle:\n    try:\n        n = int(input())\n        boucle = False\n    except ValueError :\n        print(\"Entrer un nombre entier valide\")\nprint(\"entier saisi : \", n )","execution_count":12,"outputs":[{"output_type":"stream","text":"entrer un entier\n5.2\nEntrer un nombre entier valide\n3.24\nEntrer un nombre entier valide\nac\nEntrer un nombre entier valide\n5\nentier saisi :  5\n","name":"stdout"}]},{"metadata":{"id":"HU4KMB0HcZVu","slideshow":{"slide_type":"subslide"}},"cell_type":"markdown","source":"On peut également utiliser la syntaxe : "},{"metadata":{"id":"30Knbb-Icc_G","slideshow":{"slide_type":"fragment"},"trusted":true},"cell_type":"code","source":"print('entrer un entier')\nwhile True:\n    try:\n        n = int(input())\n        break\n    except ValueError :\n        print(\"Entrer un nombre entier valide\")\n\nprint(\"entier saisi : \", n )","execution_count":13,"outputs":[{"output_type":"stream","text":"entrer un entier\nadcf\nEntrer un nombre entier valide\n15\nentier saisi :  15\n","name":"stdout"}]}],"metadata":{"colab":{"name":"02-Modules_COURS2_Exception.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyMj16QYEUuPKBSGs/j0eXnR","include_colab_link":true},"kernelspec":{"name":"python3","display_name":"Python 3"},"celltoolbar":"Slideshow"},"nbformat":4,"nbformat_minor":2}